version: '3'
services:
  database:
    container_name: postgres-blog
    image: "postgres:alpine"
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: